/**
 * System prompt instructing Gemini to analyze the document as a legal expert.
 */
export const LEGAL_ANALYSIS_SYSTEM_PROMPT = `You are a legal expert AI. Analyze the document carefully. Identify clauses by category, rate risks (High/Medium/Low/Informational) with scores 0-100, cite specific pages/paragraphs. Output structured JSON matching ClauseAnalysis schema. End with disclaimer.`;

/**
 * Dictionary of prompts for generating document summaries at different reading levels.
 */
export const DOCUMENT_SUMMARY_PROMPTS = {
  plain: 'Summarize the document in plain English, suitable for someone without legal background.',
  standard: 'Summarize the document using standard professional language.',
  attorney: 'Summarize the document with legal terminology appropriate for an attorney.'
};

/**
 * JSON schema for extracting structured clause analysis.
 */
export const CLAUSE_EXTRACTION_SCHEMA = {
  type: "array",
  items: {
    type: "object",
    properties: {
      category: { type: "string" },
      riskLevel: { type: "string", enum: ["High", "Medium", "Low", "Informational"] },
      riskScore: { type: "number" },
      citation: { type: "string" },
      explanation: { type: "string" }
    },
    required: ["category", "riskLevel", "riskScore", "citation", "explanation"]
  }
};

/**
 * JSON schema for full structured risk analysis output.
 */
export const RISK_ANALYSIS_SCHEMA = {
  type: "object",
  properties: {
    overallRiskScore: { type: "number" },
    clauses: CLAUSE_EXTRACTION_SCHEMA
  },
  required: ["overallRiskScore", "clauses"]
};

/**
 * System prompt for answering Q&A queries based on document context.
 */
export const RAG_QA_SYSTEM_PROMPT = `Only answer from provided context chunks, cite page numbers, say 'I cannot find this in the document' if not found, add disclaimer.`;

/**
 * System prompt for comparing two legal documents.
 */
export const COMPARISON_SYSTEM_PROMPT = `Compare the two documents clause by clause. Note significant differences, additions, and omissions.`;

/**
 * System prompt for generating an attorney briefing sheet.
 */
export const ATTORNEY_BRIEFING_PROMPT = `Generate a professional attorney briefing sheet in markdown format based on the analysis.`;

/**
 * System prompt for explaining a legal term in plain English.
 */
export const GLOSSARY_EXPLAIN_PROMPT = `Explain the given legal term in plain English, considering the provided context.`;

/**
 * Standard legal disclaimer to append to AI-generated legal content.
 */
export const LEGAL_DISCLAIMER = 'IMPORTANT: This analysis is generated by AI for informational purposes only. It does not constitute legal advice. Please consult a qualified attorney for professional legal guidance.';
